config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'

  devise_for :teachers, controllers:{
    registrations: 'teachers/registrations',
    sessions: 'sessions'
  }
  devise_for :students, controllers:{
    registrations: 'students/registrations',
    sessions: 'sessions'
  }

  namespace :students do
    get 'home/index'
    resources :dashboard, only: [:index]
  end

  namespace :teachers do
    get 'home/index'
    resources :dashboard, only: [:index]
  end

  get 'home/index'

end

app/models/admin.rb
class Admin < User
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
class Student < User
end

app/models/teacher.rb
class Teacher < User
end

app/models/user.rb
class User < ApplicationRecord
  extend Devise::Models
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  scope :active, -> { where(is_active: true) }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    if resource.type == 'Teacher'
      teachers_dashboard_index_path
    elsif resource.type == 'Student'
      students_dashboard_index_path
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if signed_in?
      begin
        if current_teacher
          redirect_to teachers_dashboard_index_path
        end
      end
      begin
        if current_student
          redirect_to students_dashboard_index_path
        end
      end
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  def create
    user = User.find_by(email: params_email)
    if user
      self.resource =  user # warden.authenticate!(auth_options)
      set_flash_message!(:notice, :signed_in)
      sign_in(resource_name, resource)
      user.update_attribute(:is_active, true)
      user.update_attribute(:is_deleted, false) if user.is_deleted 
      yield resource if block_given?
      respond_with resource, location: after_sign_in_path_for(resource)
    end
  end

  private

  def params_email
    email_params = params.require(:teacher).permit(:email) if params[:teacher]
    email_params = params.require(:student).permit(:email) if params[:student]
    email_params[:email].downcase
  end
end

app/controllers/students/dashboard_controller.rb
module Students
  class DashboardController < StudentsBaseController
    def index
    end
  end
end

app/controllers/students/home_controller.rb
module Students
  class HomeController < StudentsBaseController
    def index
    end
  end
end

app/controllers/students/registrations_controller.rb
module Students
  class RegistrationsController < Devise::RegistrationsController

    protected
    # The path used after sign up.
    def after_sign_up_path_for(resource)
      students_dashboard_index_path
    end
  end
end

app/controllers/students_base_controller.rb
class StudentsBaseController < ApplicationController
  layout 'student'
end

app/controllers/teachers/dashboard_controller.rb
module Teachers
  class DashboardController < TeachersBaseController
    def index
    end
  end
end

app/controllers/teachers/home_controller.rb
module Teachers
  class HomeController < TeachersBaseController
    def index
    end
  end
end

app/controllers/teachers/registrations_controller.rb
module Teachers
  class RegistrationsController < Devise::RegistrationsController

    protected
    # The path used after sign up.
    def after_sign_up_path_for(resource)
      teachers_dashboard_index_path
    end
  end
end

app/controllers/teachers_base_controller.rb
class TeachersBaseController < ApplicationController
  layout 'teacher'
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/student/home_helper.rb
module Student::HomeHelper
end

app/helpers/tutor/home_helper.rb
module Tutor::HomeHelper
end

app/views/home/index.html.erb
<h1>Home</h1>
Who You are ?
<%= link_to 'Tutor', teachers_home_index_path %>
<%= link_to 'Student', students_home_index_path %>
<br/>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tutor</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta property="og:url" content="https://aucklandrfl2020.everydayhero.com/nz/madeleine-1">
    <meta property="og:title" content="Help Chris “Tortoise” Budd make a difference">
    <meta property="og:description" content="I am privileged to work as a clinical psychologist at Starship, walking alongside liver and heart transplant families during their own much more challenging journeys. Please help me to raise money for the wonderful Starship Foundation.

	Thanks to your generosity, last year I raised $2500 running 11km! This year I have upped the stakes to a half marathon, and hope to increase donations by a similar percentage. By my maths that is a target of $4775.

	Any support would be hugely appreciated!

	">
	<meta property="og:image:type" content="image/jpeg">
	<meta property="og:type" content="image/jpeg">

	<meta property="og:image" content="https://supporter-2.cdn.everydayhero.com/pages/images/3483297/facebook_xl/blob-8b9bbdd3d2d107c901643c56ad022119.">


  </head>

  <body>
  	<h1>TEST OG Share </h1>
    <%#= yield %>
  </body>
</html>

app/views/layouts/student.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tutor</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    Student
    <% if current_student %>
      <%= menu_item "Log Out", destroy_student_session_path, method: :delete %>
    <% else %>
      <%= link_to 'Login', new_student_session_path %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/layouts/teacher.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tutor</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    Teacher
    <% if current_teacher %>
      <%= menu_item "Log Out", destroy_teacher_session_path, method: :delete %>
    <% else %>
      <%= link_to 'Login', new_teacher_session_path %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/students/dashboard/index.html.erb
Welcome Student

app/views/students/home/index.html.erb
<h1>Student</h1>

app/views/teachers/dashboard/index.html.erb
<h1>Welcome Page for Teachers</h1>

app/views/teachers/home/index.html.erb
<h1>Tutor</h1>